=== Ashraf-Khabar/StudentDocumentGenerator/Affiche des notes/notes.dtd
<!ELEMENT notes (note*)>
<!ELEMENT note (CNE,FirstName,LastName,ClassName,ModuleName,NoteElement)>
<!ELEMENT CNE (#PCDATA)>
<!ELEMENT FirstName (#PCDATA)>
<!ELEMENT LastName (#PCDATA)>
<!ELEMENT ClassName (#PCDATA)>
<!ELEMENT ModuleName (#PCDATA)>
<!ELEMENT NoteElement (#PCDATA)>

=== Ashraf-Khabar/StudentDocumentGenerator/affiche_des_notes/Ginf2_Notes.xml
<?xml version="1.0"?>
<!DOCTYPE notes SYSTEM "notes.dtd">
<notes>
    <note>
        <CNE>44526656</CNE>
        <FirstName>ashraf</FirstName>
        <LastName>khabar</LastName>
        <ClassName>GINF2</ClassName>
        <ModuleName>ProgrammationOrienteeObjet/XML</ModuleName>
        <NoteElement>17</NoteElement>
    </note>
     <note>
        <CNE>44526656</CNE>
        <FirstName>hassan</FirstName>
        <LastName>said</LastName>
        <ClassName>GINF2</ClassName>
        <ModuleName>ProgrammationOrienteeObjet/XML</ModuleName>
        <NoteElement>2</NoteElement>
    </note>
      <note>
        <CNE>44526656</CNE>
        <FirstName>mouad</FirstName>
        <LastName>adil</LastName>
        <ClassName>GINF2</ClassName>
        <ModuleName>ProgrammationOrienteeObjet/XML</ModuleName>
        <NoteElement>9</NoteElement>
    </note>
    <note>
        <CNE>24585858</CNE>
        <FirstName>zakaria</FirstName>
        <LastName>dkhissi</LastName>
        <ClassName>GINF2</ClassName>
        <ModuleName>ProgrammationOrienteeObjet/XML</ModuleName>
        <NoteElement>20</NoteElement>
    </note>
</notes>
